# Generated by Django 2.2.3 on 2020-08-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destinos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='titulo')),
                ('description', models.CharField(max_length=100, verbose_name='descripcion')),
                ('images', models.ImageField(upload_to='viajes/images')),
                ('puntuation', models.CharField(max_length=2, verbose_name='puntaje')),
                ('coments', models.TextField(max_length=200, verbose_name='comentarios')),
                ('restaurant', models.TextField(max_length=200, verbose_name='restaurantes')),
            ],
        ),
    ]
